### ISSUE TITLE
Build Canceled: Broccoli Builder ran into an error with Babel plugin

### ISSUE THREAD

**Issue by shortthirdman** [ember-cli/broccoli-builder#12]
I have been running into this problem since a few days back and have not been able to find the real issue (root cause).
My enviroment specs:
Node version 6.9.5
npm version 3.10.10
Ember CLI version 2.11.1
OS: Windows 8 SL (64bit)
Heres the screenshot:

![image](https://user-images.githubusercontent.com/5894985/27535263-c10a763e-5a87-11e7-8360-e9ab27458989.png)

**Comment by shortthirdman** [comment]
Here's the much described output when `ember build` or `ember serve`:
Build error

The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appAndDependencies)] failed with:
Error: Build Canceled: Broccoli Builder ran into an error with Babel plugin. ðŸ’¥
    at new BroccoliBuildError (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\broccoli-builder\lib\broccoli-build-error.js:40:9)
    at E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\broccoli-builder\lib\builder.js:168:19
    at tryCatch (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:216:12)
    at invokeCallback (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:231:13)
    at publish (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:199:7)
    at publishRejection (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:134:3)
    at flush (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:42:10)
    at BroccoliMergeTrees (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:36:53)
    at mergeTrees (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\broccoli\merge-trees.js:46:18)
    at EmberApp.appAndDependencies (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1130:10)
    at EmberApp.javascript (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1244:34)
    at EmberApp.toArray (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1674:10)
    at EmberApp.toTree (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:30)
    at module.exports (E:\Projects\NetStar 5\netstar-portal-ui\ember-cli-build.js:41:14)
    at CoreObject.setupBroccoliBuilder (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\models\builder.js:84:19)
    at CoreObject.init (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\models\builder.js:64:10)
    at CoreObject.superWrapper [as init] (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at CoreObject.Class (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\core-object\core-object.js:32:33)
    at CoreObject.run (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\lib\commands\serve.js:76:24
    at tryCatch (E:\Projects\NetStar 5\netstar-portal-ui\node_modules\ember-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:216:12)

**Comment by plwalters** [comment]
Running in to the same problem as well any insight  @shortthirdman if you found a fix?

**Comment by jeffjewiss** [comment]
I'm fairly certain this is due to https://github.com/ember-cli/broccoli-builder/pull/10 and was introduced in `0.18.5`.

I think the above PR is causing warnings/errors in add-ons to be hidden and `Build Canceled: Broccoli Builder ran into an error with…` instead. This has been reported on an addon I work on (https://github.com/jeffjewiss/ember-cli-postcss/issues/113) and I also noticed it while working on said add-on.

Is this something that can even be fixed by add-on authors? It potentially looks like something to be handled by `ember-cli` and how it handles Broccoli build errors.

I couldn't find a short term solution to this as even reverting `ember-cli` to `2.12.0` uses `broccoli-builder": "^0.18.3"` and resolves to the version with the issue. Short of reverting this change and publishing another version of `broccoli-builder` I'm not sure how to fix this.

**Comment by plwalters** [comment]
Agreed that it seems to be squelching errors elsewhere.  Thanks for the insight and your help with maintaining.

**Comment by xdumaine** [comment]
@jeffjewiss I'm +1 for reverting the change and publishing a patch. From our perspective this is a breaking change published as a patch version, so it should be reverted. It's caused a lot of frustration for developers on our end this week.

**Comment by devinaction** [comment]
Similar issue on my end too. Any fixes?

**Comment by shortthirdman** [comment]
@PWKad I got it fixed by using an already installed node_modules folder since when i install it on my machine, it gave the issue.

**Comment by xdumaine** [comment]
@shortthirdman why did you close the issue? It's not fixed...

**Comment by shortthirdman** [comment]
@xdumaine Ok reopening it. In my case it was solved. Higher version of Ember CLI was the root cause.

**Comment by jeffjewiss** [comment]
I'm pretty sure this issue has been resolved since the release of v0.18.8. @xdumaine are you still seeing broccoli builder errors instead of the specific add-on errors?

**Comment by jeffrey008** [comment]
This error message is gone after upgrading to ember-cli@2.15. There was some syntax error in my addon but broccoli couldn't tell it explicitly.
