### ISSUE TITLE
broccoliBuilderErrorStack: Error: ENOENT: no such file or directory 

### ISSUE THREAD

**Issue by PankajWorks** [ember-cli/broccoli-builder#31]
Hi All,
I ran into the following error while ember serve. Is there something i am missing
ERROR Summary:
```
  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, lstat '/Users/pankaj.singh/GitHub/qaas-dashboard-ui/tmp/funnel-input_base_path-mg0ILCpx.tmp/index.html'
    at Object.fs.lstatSync (fs.js:961:11)
    at symlink (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/symlink-or-copy/index.js:99:26)
    at Function.symlinkOrCopySync [as sync] (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/symlink-or-copy/index.js:85:5)
    at Funnel._copy (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:494:19)
    at Funnel.processFile (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:477:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:390:12)
    at Funnel.<anonymous> (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:344:10)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:343:11)
    at Funnel.build (/Users/pankaj.singh/GitHub/qaas-dashboard-ui/node_modules/broccoli-funnel/index.js:259:10)
  - codeFrame: ENOENT: no such file or directory, lstat '/Users/pankaj.singh/GitHub/qaas-dashboard-ui/tmp/funnel-input_base_path-mg0ILCpx.tmp/index.html'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, lstat '/Users/pankaj.singh/GitHub/qaas-dashboard-ui/tmp/funnel-input_base_path-mg0ILCpx.tmp/index.html'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, lstat '/Users/pankaj.singh/GitHub/qaas-dashboard-ui/tmp/funnel-input_base_path-mg0ILCpx.tmp/index.html'
  - name: Error
  - nodeAnnotation: Funnel (test index)
  - nodeName: Funnel
  - originalErrorMessage: ENOENT: no such file or directory, lstat '/Users/pankaj.singh/GitHub/qaas-dashboard-ui/tmp/funnel-input_base_path-mg0ILCpx.tmp/index.html'
```

**Comment by nagaperla** [comment]
Any solutions for the above issue?
